% S00b_prep_data
% s00c_fillCorruptCuts
% S01_BruntVaisRossby
% S02_infer_fields
% S03_contours
% S05a_correctZeroCrossTemp
% S05_track_eddies
% addpath(genpath('./'))
% sleep(5*60*60)
 S04_filter_eddies
% S05_track_eddies
%  S06_init_output_maps
%  S08_analyze_tracks
% try
%     S09_plotsNew
% end
% try
%     S09_drawPlots
% end
